```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
source("scripts/bresat.R")
```

```{r}
datdir <- "data/maaslin_output/ibd"


files <- c("type1_dom_libnorm_counts_01maaslinpaths.csv", "type1_dom_metadata.csv", "type2_dom_libnorm_counts_01maaslinpaths.csv", "type2_dom_metadata.csv", "type3_dom_libnorm_counts_01maaslinpaths.csv", "type3_dom_metadata.csv", "noAA_allIBD_libnorm_counts_01maaslinpaths.csv",
"withAA_allIBD_libnorm_counts_01maaslinpaths.csv", "allIBD_metdata.csv")

alldf <- lapply(files, function(f){
  df <- read.csv(file.path(datdir, f), header=TRUE, row.names = 1)
})

names(alldf) <- c("type1_counts", "type1_metadata",
                  "type2_counts", "type2_metadata",
                  "type3_counts", "type3_metadata",
                  "noAA_allIBD_counts", "withAA_allIBD_count", "allIBD_metdata")

```

```{r}
alldf.counts <- alldf[c(1,3,5,7,8)]


bresat<-NULL
bresat <- lapply(alldf.counts, function(df) {
    sig.ranksum(as.matrix(df), ns=1:nrow(df), full.return=TRUE)
  })

roi<-NULL
roi<- mclapply(bresat, function(bs) {
    random.ranks(bs, n=10000, mc.cores = 80)
  }, mc.cores=80)


for (nms in names(bresat)){
    bresat[[nms]]$roi<-roi[[nms]]
}

### define roi categories
roi.cat <- NULL
roi.cat<- mclapply(bresat, function(bs) {
    define.roi.regions(bs, bs$roi)
  }, mc.cores=80)


for (nms in names(bresat)){
    bresat[[nms]]$roi.cat<-roi.cat[[nms]]
}

saveRDS(bresat, "data/maaslin_output/ibd/fdr01_ibd_bresat.rds")
```

```{r}

bresat <- readRDS("data/maaslin_output/ibd/fdr01_ibd_bresat.rds")


alldf.metadata <- alldf[c(2,4,6,9)]

disease_colors <- setNames(c("#FF5586", "lightblue"), c("IBD", "healthy"))
study_colors <- setNames(c( "#8dd3c7", "#fb8072", "#fda"), c("PRJEB1220", "PRJNA385949", "PRJEB5224"))



type_colors_fixed <- list(
    type1 = colorRampPalette(c("#E8F7FC", "#66CCEE", "#1A5570"))(100),    
    type2 = colorRampPalette(c("#F7F4E0", "#CCBB44", "#665D22"))(100),    
    type3 = colorRampPalette(c("#F2E0EA", "#AA3377", "#551A3B"))(100)   # 
)

# map_to_palette <- function(x, palette) {
#     # Normalize values between 0 and 1
#     x_norm <- (x - min(x, na.rm = TRUE)) / 
#               (max(x, na.rm = TRUE) - min(x, na.rm = TRUE))
#     # Map to color palette index
#     idx <- round(x_norm * 99) + 1
#     palette[idx]
# }

map_to_palette_fixed <- function(x, palette, min_val = 0, max_val = 1) {
  # Map values to indices based on fixed range
  idx <- round((x - min_val) / (max_val - min_val) * 99) + 1
  
  # Ensure indices are within bounds
  idx[idx < 1] <- 1
  idx[idx > 100] <- 100
  
  palette[idx]
}


alldf.metadata <- lapply(alldf.metadata, function(df){
  df <- df[, c("disease", "study", "type1", "type2", "type3" )]
  df$disease <- disease_colors[df$disease]
  df$study <- study_colors[df$study]

  # Apply color mapping to each type column
  df$type1 <- map_to_palette_fixed(df$type1, type_colors_fixed$type1)
  df$type2 <- map_to_palette_fixed(df$type2, type_colors_fixed$type2)
  df$type3 <- map_to_palette_fixed(df$type3, type_colors_fixed$type3)
  
  return(df)
  
})

names(alldf.metadata) <- names(bresat)[1:4]
alldf.metadata <- c(alldf.metadata, alldf.metadata[4])
names(alldf.metadata)[5] <- names(bresat)[5]
```

```{r}
library(gridBase)
library(gridExtra)
library(grid)

source("scripts/mybresat.R")
source("scripts/myheatmap.R")
pdf("figures/exp05/1_figures/figure6DF_bresat_heatmaps_ibd.pdf" )
for (nms in names(bresat)){
    plot.new(); grid.newpage()
    create.bresat.heatmap(bs=bresat[[nms]], cl.df=alldf.metadata[[nms]], cl.var = c("disease", "study", "type1", "type2", "type3" ), cl.height = 2,
                           title=nms)
  }
dev.off()
```